name: project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  freezed_annotation: ^2.2.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  google_sign_in: ^6.0.2
  firebase_storage: ^11.2.2
  dartz: ^0.10.0
  hooks_riverpod: ^2.3.6
  flutter_signin_button: ^2.0.0
  firebase_dynamic_links: ^5.3.3
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.3.2
  build_runner: ^2.1.5

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - images/yemek.jpg
  - images/logo.png
  - images/splash.png

